server:
  port: 8888


spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/noend?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.jdbc.Driver
  quartz:
    #相关属性配置
    properties:
      org:
        quartz:
          scheduler:
            instanceName: clusteredScheduler
            instanceId: AUTO
          jobStore:
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            tablePrefix: QRTZ_
            isClustered: true
            clusterCheckinInterval: 10000
            useProperties: false
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 10
            threadPriority: 5
            threadsInheritContextClassLoaderOfInitializingThread: true
      #数据库方式
    job-store-type: jdbc
#  # freemarker
  freemarker:
    # 是否开启缓存 生产环境设置true
    cache: true
    charset: UTF-8
    content-type: text/html
    suffix: .html
    template-loader-path: classpath:/templates
    settings:
      # 解决页面中取空值出现的异常
      classic_compatible: true
      template_update_delay: 0
# 分页配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.su.model

# mybatis日志输出级别
logging:
  level:
    com.zxq.dao: info